name: "Install-dependencies-and-RHEED camera script"
description: "Install RHEED camera script and its dependencies"
runs:
  using: "composite"
  steps:
    - name: Install-dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -e .[ci]
      shell: bash
